export const typeEmojiMap = {
    bug: "🐞",
    dark: "🌙",
    dragon: "🐲",
    electric: "⚡",
    fairy: "✨",
    fighting: "🥊",
    fire: "🔥",
    flying: "🌪️",
    ghost: "👻",
    grass: "🌿",
    ground: "🗿",
    ice: "❄️",
    normal: "⚪",
    poison: "☠️",
    psychic: "🧠",
    rock: "⛰️",
    steel: "🛡️",
    water: "💧"
  };

  export const typeColorMap = {
    grass: "#d2f2c2",
    poison: "#f7cdf7",
    fire: "#ffd1b5",
    flying: "#eae3ff",
    water: "#c2f3ff",
    bug: "#e0e8a2",
    normal: "#e6e6c3",
    electric: "#fff1ba",
    ground: "#e0ccb1",
    fighting: "#fcada9",
    psychic: "#ffc9da",
    rock: "#f0e09c",
    fairy: "#ffdee5",
    steel: "#e6eaf0",
    ice: "#e8feff",
    ghost: "#dbbaff",
    dragon: "#c4bdff",
    dark: "#a9abb0"
  };

  export const altTypeColorMap = {
    normal: '#A8A77A',
    fire: '#EE8130',
    water: '#6390F0',
    electric: '#F7D02C',
    grass: '#7AC74C',
    ice: '#96D9D6',
    fighting: '#C22E28',
    poison: '#A33EA1',
    ground: '#E2BF65',
    flying: '#A98FF3',
    psychic: '#F95587',
    bug: '#A6B91A',
    rock: '#B6A136',
    ghost: '#735797',
    dragon: '#6F35FC',
    dark: '#705746',
    steel: '#B7B7CE',
    fairy: '#D685AD',
  };